/**
 * Generates context/component-index.md: for each component under src/components/**, its
 * exported name(s), the hooks it imports (split out API-data hooks from '@/hooks/api'), and
 * its own Props interface fields if one is declared in the file.
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { Project } from 'ts-morph'
import { writeArtifact } from './lib/manifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
export const OUTPUT_PATH = path.join(ROOT, 'context', 'component-index.md')

interface ComponentEntry {
  file: string
  exportedNames: string[]
  apiHooks: string[]
  otherHooks: string[]
  propsFields: string[]
  lineCount: number
}

export function generateComponentIndex(): { content: string; componentCount: number } {
  const project = new Project({ tsConfigFilePath: path.join(ROOT, 'tsconfig.json') })
  const sourceFiles = project
    .getSourceFiles(['src/components/**/*.tsx'])
    .filter((sf) => !sf.getFilePath().endsWith('.test.tsx'))
    .sort((a, b) => a.getFilePath().localeCompare(b.getFilePath()))

  const entries: ComponentEntry[] = sourceFiles.map((sourceFile) => {
    const relPath = path.relative(ROOT, sourceFile.getFilePath())

    const exportedNames = [...sourceFile.getExportedDeclarations().keys()].filter(
      (name) => name !== 'default'
    )
    if (exportedNames.length === 0) {
      // default-only export: fall back to the file's base name (matches convention here)
      exportedNames.push(path.basename(relPath, '.tsx'))
    }

    const apiHooks: string[] = []
    const otherHooks: string[] = []
    for (const imp of sourceFile.getImportDeclarations()) {
      const spec = imp.getModuleSpecifierValue()
      const names = [
        ...imp.getNamedImports().map((n) => n.getName()),
        ...(imp.getDefaultImport() ? [imp.getDefaultImport()!.getText()] : []),
      ].filter((n) => n.startsWith('use'))
      if (names.length === 0) continue
      if (spec === '@/hooks/api') apiHooks.push(...names)
      else otherHooks.push(...names)
    }

    const propsFields: string[] = []
    const propsInterface = sourceFile
      .getInterfaces()
      .find((i) => /Props$/.test(i.getName()))
    if (propsInterface) {
      for (const prop of propsInterface.getProperties()) {
        propsFields.push(`${prop.getName()}${prop.hasQuestionToken() ? '?' : ''}: ${prop.getTypeNode()?.getText() ?? prop.getType().getText()}`)
      }
    }

    return {
      file: relPath,
      exportedNames,
      apiHooks: [...new Set(apiHooks)].sort(),
      otherHooks: [...new Set(otherHooks)].sort(),
      propsFields,
      lineCount: sourceFile.getEndLineNumber(),
    }
  })

  const lines: string[] = [
    '# Component index',
    '',
    "> Generated by `scripts/context/component-index.ts` — do not hand-edit. Run `yarn context:build`.",
    '',
  ]

  for (const e of entries) {
    lines.push(`## \`${e.exportedNames.join(', ')}\``, '', `- File: [${e.file}](../${e.file}) (${e.lineCount} lines)`)
    lines.push(`- API hooks used: ${e.apiHooks.length > 0 ? e.apiHooks.join(', ') : '—'}`)
    lines.push(`- Other hooks used: ${e.otherHooks.length > 0 ? e.otherHooks.join(', ') : '—'}`)
    if (e.propsFields.length > 0) {
      lines.push('- Props:')
      for (const f of e.propsFields) lines.push(`  - \`${f}\``)
    }
    lines.push('')
  }

  return { content: lines.join('\n'), componentCount: entries.length }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { content, componentCount } = generateComponentIndex()
  const sha256 = writeArtifact(OUTPUT_PATH, content)
  console.log(`Wrote context/component-index.md (${componentCount} components, sha256 ${sha256.slice(0, 12)}...)`)
}
