/**
 * Generates context/contract-drift.md: compares component schemas in the vendored
 * contracts/openapi.json against the manually mirrored interfaces in src/lib/types.ts.
 * WARNING artifact only — a non-empty drift list never fails `yarn context:build` (see
 * docs/adr/0007-manual-types-mirror.md). Matching is by exact schema/interface name; this
 * is a best-effort heuristic, not a full structural type comparison.
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFileSync, existsSync } from 'node:fs'
import { Project } from 'ts-morph'
import { writeArtifact } from './lib/manifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
const CONTRACT_PATH = path.join(ROOT, 'contracts', 'openapi.json')
const TYPES_PATH = path.join(ROOT, 'src', 'lib', 'types.ts')
export const OUTPUT_PATH = path.join(ROOT, 'context', 'contract-drift.md')

interface OpenapiSchema {
  properties?: Record<string, unknown>
}

interface DriftEntry {
  schemaName: string
  matchedInterface: string | null
  missingFromTypes: string[]
  extraInTypes: string[]
}

const SCHEMA_INTERFACE_ALIASES: Record<string, string> = {
  Error: 'ApiErrorResponse',
  User: 'UserProfile',
}

export function contractExists(): boolean {
  return existsSync(CONTRACT_PATH)
}

export function generateContractDrift(): { content: string; driftCount: number } {
  const contract = JSON.parse(readFileSync(CONTRACT_PATH, 'utf8')) as {
    components?: { schemas?: Record<string, OpenapiSchema> }
  }
  const schemas = contract.components?.schemas ?? {}

  const project = new Project({ tsConfigFilePath: path.join(ROOT, 'tsconfig.json') })
  const sourceFile = project.addSourceFileAtPath(TYPES_PATH)
  const interfaces = new Map(sourceFile.getInterfaces().map((i) => [i.getName(), i]))

  const entries: DriftEntry[] = []
  for (const [schemaName, schema] of Object.entries(schemas)) {
    const interfaceName = SCHEMA_INTERFACE_ALIASES[schemaName] ?? schemaName
    const iface = interfaces.get(interfaceName)
    const schemaFields = new Set(Object.keys(schema.properties ?? {}))
    if (!iface) {
      entries.push({ schemaName, matchedInterface: null, missingFromTypes: [...schemaFields], extraInTypes: [] })
      continue
    }
    const typeFields = new Set(iface.getProperties().map((p) => p.getName()))
    entries.push({
      schemaName,
      matchedInterface: interfaceName,
      missingFromTypes: [...schemaFields].filter((f) => !typeFields.has(f)),
      extraInTypes: [...typeFields].filter((f) => !schemaFields.has(f)),
    })
  }

  const matchedInterfaces = new Set(
    entries.flatMap((entry) => (entry.matchedInterface ? [entry.matchedInterface] : []))
  )
  const unmatchedInterfaces = [...interfaces.keys()].filter(
    (name) => !schemas[name] && !matchedInterfaces.has(name)
  )
  const driftCount = entries.filter(
    (e) => e.matchedInterface === null || e.missingFromTypes.length > 0
  ).length

  const lines: string[] = [
    '# Contract drift report',
    '',
    "> Generated by `scripts/context/contract-drift.ts` — do not hand-edit. Run `yarn context:build`.",
    '> WARNING-only artifact: a non-empty drift list never fails the build (see',
    '> `docs/adr/0007-manual-types-mirror.md`). `src/lib/types.ts` remains the source of truth.',
    '',
    `- OpenAPI component schemas: ${Object.keys(schemas).length}`,
    `- Schemas with drift or no matching interface: ${driftCount}`,
    '',
  ]

  for (const e of entries) {
    lines.push(`## \`${e.schemaName}\``, '')
    if (!e.matchedInterface) {
      lines.push(`No interface named \`${e.schemaName}\` found in \`src/lib/types.ts\`.`, '')
      continue
    }
    if (e.matchedInterface !== e.schemaName) {
      lines.push(`Matched to \`${e.matchedInterface}\` in \`src/lib/types.ts\`.`, '')
    }
    if (e.missingFromTypes.length === 0 && e.extraInTypes.length === 0) {
      lines.push('In sync. ✅', '')
      continue
    }
    if (e.missingFromTypes.length > 0) {
      lines.push(`- In OpenAPI schema but missing from \`types.ts\`: ${e.missingFromTypes.map((f) => `\`${f}\``).join(', ')}`)
    }
    if (e.extraInTypes.length > 0) {
      lines.push(`- In \`types.ts\` but not in the OpenAPI schema: ${e.extraInTypes.map((f) => `\`${f}\``).join(', ')}`)
    }
    lines.push('')
  }

  if (unmatchedInterfaces.length > 0) {
    lines.push(
      '## Interfaces in types.ts with no matching OpenAPI schema name',
      '',
      '(Not necessarily a problem — many app-only shapes have no 1:1 backend schema.)',
      '',
      ...unmatchedInterfaces.map((name) => `- \`${name}\``),
      ''
    )
  }

  return { content: lines.join('\n'), driftCount }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (!contractExists()) {
    console.error('contracts/openapi.json not found — run `yarn contract:pull` first (dev-machine only).')
    process.exit(1)
  }
  const { content, driftCount } = generateContractDrift()
  const sha256 = writeArtifact(OUTPUT_PATH, content)
  console.log(`Wrote context/contract-drift.md (${driftCount} schemas with drift, sha256 ${sha256.slice(0, 12)}...)`)
}
