/**
 * Generates context/module-graph.json (full dependency-cruiser output) and
 * context/module-graph.md (human-readable summary + any architecture-rule violations),
 * enforcing the rules from AGENTS.md:
 * - components/app pages must not import src/lib/api/* or api-client.ts directly
 *   (must go through src/hooks/api.ts)
 * - components must not import src/lib/mock-api.ts directly
 * - only src/lib/api/http.ts imports axios
 * - no circular dependencies
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { cruise, type ICruiseOptions, type ICruiseResult, type IModule } from 'dependency-cruiser'
import { stableStringify, writeArtifact } from './lib/manifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
export const JSON_OUTPUT_PATH = path.join(ROOT, 'context', 'module-graph.json')
export const MD_OUTPUT_PATH = path.join(ROOT, 'context', 'module-graph.md')

export type StableCruiseResult = Omit<ICruiseResult, 'summary'> & {
  summary: Omit<ICruiseResult['summary'], 'environment'>
}

const cruiseOptions: ICruiseOptions = {
  includeOnly: '^src',
  validate: true,
  tsConfig: { fileName: path.join(ROOT, 'tsconfig.json') },
  ruleSet: {
    forbidden: [
      {
        name: 'no-circular',
        severity: 'error',
        comment: 'No circular dependencies anywhere under src/.',
        from: {},
        to: { circular: true },
      },
      {
        name: 'components-app-no-direct-api-client',
        severity: 'error',
        comment:
          'components/ and app/ must call the backend only via src/hooks/api.ts, never src/lib/api/* or api-client.ts directly.',
        from: { path: '^src/(components|app)' },
        to: { path: '^src/lib/(api-client\\.ts$|api/)' },
      },
      {
        name: 'components-no-mock-import',
        severity: 'error',
        comment: 'components/ must not import src/lib/mock-api.ts directly.',
        from: { path: '^src/components' },
        to: { path: '^src/lib/mock-api\\.ts$' },
      },
      {
        name: 'only-http-imports-axios',
        severity: 'error',
        comment: 'Only src/lib/api/http.ts may import axios directly.',
        from: { path: '^src/(?!lib/api/http\\.ts$)' },
        to: { path: 'node_modules/axios' },
      },
    ],
  },
}

export function normalizeCruiseResult(result: ICruiseResult): StableCruiseResult {
  const { environment, optionsUsed, ...summary } = result.summary
  void environment
  return {
    ...result,
    summary: {
      ...summary,
      optionsUsed: {
        ...optionsUsed,
        baseDir: '.',
        tsConfig: optionsUsed.tsConfig
          ? { ...optionsUsed.tsConfig, fileName: 'tsconfig.json' }
          : undefined,
      },
    },
  }
}

export async function generateModuleGraph(): Promise<{
  result: StableCruiseResult
  violationCount: number
}> {
  const cruiseResult = await cruise([path.join(ROOT, 'src')], cruiseOptions)
  const output = normalizeCruiseResult(cruiseResult.output as ICruiseResult)
  const violations = output.modules.flatMap((m: IModule) =>
    (m.dependencies ?? []).filter((d) => (d.rules ?? []).length > 0)
  )
  return { result: output, violationCount: violations.length }
}

export function buildMarkdownSummary(result: StableCruiseResult, violationCount: number): string {
  const lines: string[] = [
    '# Module graph',
    '',
    '> Generated by `scripts/context/module-graph.ts` (dependency-cruiser) — do not',
    '> hand-edit. Run `yarn context:build`. Full graph: `context/module-graph.json`.',
    '',
    `- Modules analyzed: ${result.modules.length}`,
    `- Architecture rule violations: ${violationCount}`,
    '',
  ]

  if (violationCount > 0) {
    lines.push('## Violations', '')
    for (const module of result.modules) {
      for (const dep of module.dependencies ?? []) {
        for (const rule of dep.rules ?? []) {
          lines.push(`- **${rule.name}**: \`${module.source}\` → \`${dep.resolved}\``)
        }
      }
    }
    lines.push('')
  } else {
    lines.push('No violations of the encoded architecture rules. ✅', '')
  }

  return lines.join('\n')
}

async function main(): Promise<void> {
  const { result, violationCount } = await generateModuleGraph()
  const jsonSha = writeArtifact(JSON_OUTPUT_PATH, stableStringify(result))
  const mdSha = writeArtifact(MD_OUTPUT_PATH, buildMarkdownSummary(result, violationCount))
  console.log(
    `Wrote context/module-graph.json (sha256 ${jsonSha.slice(0, 12)}...) and module-graph.md (sha256 ${mdSha.slice(0, 12)}...)`
  )
  if (violationCount > 0) {
    console.error(`⚠ ${violationCount} architecture rule violation(s) found — see context/module-graph.md`)
    process.exitCode = 1
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main()
}
