/**
 * Generates context/route-map.md: every Next.js App Router page/layout under src/app/**,
 * its resolved route path, whether it's a 'use client' boundary, and which components (from
 * '@/components/*') it imports directly.
 */
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { Project } from 'ts-morph'
import { writeArtifact } from './lib/manifest.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
const APP_DIR = path.join(ROOT, 'src', 'app')
export const OUTPUT_PATH = path.join(ROOT, 'context', 'route-map.md')

interface RouteEntry {
  routePath: string
  fileType: 'page' | 'layout'
  isClient: boolean
  file: string
  components: string[]
}

/** Convert an app-router file path to its URL route (route groups in parens are dropped). */
function toRoutePath(filePath: string): string {
  const relDir = path.relative(APP_DIR, path.dirname(filePath))
  if (relDir === '') return '/'
  const segments = relDir
    .split(path.sep)
    .filter((seg) => !(seg.startsWith('(') && seg.endsWith(')')))
  return '/' + segments.join('/')
}

export function generateRouteMap(): { content: string; routeCount: number } {
  const project = new Project({ tsConfigFilePath: path.join(ROOT, 'tsconfig.json') })
  const sourceFiles = project
    .getSourceFiles(['src/app/**/page.tsx', 'src/app/**/layout.tsx'])
    .sort((a, b) => a.getFilePath().localeCompare(b.getFilePath()))

  const entries: RouteEntry[] = sourceFiles.map((sourceFile) => {
    const filePath = sourceFile.getFilePath()
    const relPath = path.relative(ROOT, filePath)
    const fileType = path.basename(filePath).startsWith('layout') ? 'layout' : 'page'
    const firstStatementText = sourceFile.getFullText().trimStart().slice(0, 20)
    const isClient = firstStatementText.includes("'use client'") || firstStatementText.includes('"use client"')

    const components = sourceFile
      .getImportDeclarations()
      .filter((imp) => imp.getModuleSpecifierValue().startsWith('@/components/'))
      .map((imp) => imp.getModuleSpecifierValue().replace('@/components/', ''))
      .sort()

    return {
      routePath: toRoutePath(filePath),
      fileType,
      isClient,
      file: relPath,
      components,
    }
  })

  const lines: string[] = [
    '# Route map',
    '',
    "> Generated by `scripts/context/route-map.ts` — do not hand-edit. Run `yarn context:build`.",
    '',
    '| Route | Type | Client boundary | Components imported | File |',
    '| ----- | ---- | ---------------- | -------------------- | ---- |',
    ...entries.map(
      (e) =>
        `| \`${e.routePath}\` | ${e.fileType} | ${e.isClient ? "'use client'" : '—'} | ${
          e.components.length > 0 ? e.components.join(', ') : '—'
        } | [${e.file}](../${e.file}) |`
    ),
    '',
  ]

  return { content: lines.join('\n'), routeCount: entries.length }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { content, routeCount } = generateRouteMap()
  const sha256 = writeArtifact(OUTPUT_PATH, content)
  console.log(`Wrote context/route-map.md (${routeCount} routes, sha256 ${sha256.slice(0, 12)}...)`)
}
